---
repos:
  - repo: https://github.com/HRC-PhD/.github
    rev: v0.37.0
    hooks:
      - id: hrc-phd-hooks
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 42.19.5
    hooks:
      - id: renovate-config-validator
        args:
          - renovate/default-config.json5
