---
repos:
  - repo: https://github.com/HRC-PhD/.github
    rev: v0.8.0
    hooks:
      - id: hrc-phd-hooks
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.42.2
    hooks:
      - id: renovate-config-validator
        args:
          - renovate/default-config.json
